# Generated by Django 2.1 on 2018-10-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='latest_uid',
            field=models.IntegerField(default=7344),
            preserve_default=False,
        ),
    ]
