# Generated by Django 2.1 on 2018-11-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_auto_20181012_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='phishing',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
